services:
  - type: web
    name: lumivst-backend
    env: python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
databases:
  - name: lumivst-db
    databaseName: lumivst
    user: lumivst
